const en = {
  title: 'adrianobr — Android apps and games', description: 'Digital products to play, create and organize. Discover adrianobr Android apps and games.',
  skip: 'Skip to apps', home: 'Home', catalog: 'Apps & games', about: 'About', header: 'Play. Create. Organize.|A more enjoyable Android.', eyebrow: 'ANDROID PORTFOLIO', heroTitle: 'Digital products|to play, create and organize.', intro: 'Android apps and games made with care for your daily life.|Small ideas, great experiences.',
  featured: 'Featured apps and games', all: 'All', games: 'Games', apps: 'Apps', play: 'View on Google Play', projects: 'projects', noScript: 'All projects are available to browse on this page.', aboutSummary: 'About', aboutTitle: 'Made with care, by adrianobr.', aboutText: 'Independent Android developer. I create apps and games to make everyday life more practical and enjoyable.', accessTitle: 'Unauthorized access', accessText: 'This page is not available directly. You will be taken to the main portal.', accessLink: 'Go to the home page',
  arrow: 'Challenge your logic with|arrow puzzles.', stellar: 'Protect the stellar core|and overcome every challenge.', tasks: 'Organize your routine in a|simple and efficient way.', ring: 'Spin, reverse and challenge|your reflexes.', notes: 'Capture ideas and organize|your notes quickly.', bean: 'Explore brewing methods|and discover your coffee.'
};

const localized = {
  'pt-BR': { title:'adrianobr — Apps e jogos para Android', description:'Produtos digitais para jogar, criar e organizar. Conheça os aplicativos e jogos Android de adrianobr.', skip:'Pular para os aplicativos', home:'Início', catalog:'Apps e jogos', about:'Sobre', header:'Jogar. Criar. Organizar.|Um Android mais divertido.', eyebrow:'PORTFÓLIO ANDROID', heroTitle:'Produtos digitais|para jogar, criar e organizar.', intro:'Apps e jogos Android feitos com paixão para o seu dia a dia.|Pequenas ideias, grandes experiências.', featured:'Apps e jogos em destaque', all:'Todos', games:'Jogos', apps:'Aplicativos', play:'Ver no Google Play', projects:'projetos', noScript:'Todos os projetos estão disponíveis para consulta nesta página.', aboutSummary:'Sobre', aboutTitle:'Feito com cuidado, por adrianobr.', aboutText:'Desenvolvedor Android independente. Crio aplicativos e jogos para tornar o dia a dia mais prático e divertido.', accessTitle:'Acesso não autorizado', accessText:'Esta página não está disponível diretamente. Você será levado ao portal principal.', accessLink:'Ir para a página inicial', arrow:'Desafie sua lógica com|quebra-cabeças de setas.', stellar:'Proteja o núcleo estelar|e supere cada desafio.', tasks:'Organize sua rotina de forma|simples e eficiente.', ring:'Gire, inverta e desafie|os seus reflexos.', notes:'Anote ideias e organize|seus registros rapidamente.', bean:'Explore métodos de preparo|e descubra o seu café.' },
  'pt-PT': { home:'Início', catalog:'Apps e jogos', about:'Sobre', header:'Jogar. Criar. Organizar.|Um Android mais divertido.', heroTitle:'Produtos digitais|para jogar, criar e organizar.', intro:'Aplicações e jogos Android feitos para o seu dia a dia.|Pequenas ideias, grandes experiências.', featured:'Aplicações e jogos em destaque', apps:'Aplicações', play:'Ver no Google Play', aboutTitle:'Feito com cuidado, por adrianobr.', aboutText:'Programador Android independente. Crio aplicações e jogos para tornar o dia a dia mais prático e divertido.', accessTitle:'Acesso não autorizado', accessText:'Esta página não está disponível diretamente. Será encaminhado para o portal principal.', accessLink:'Ir para a página inicial' },
  es: { title:'adrianobr — Apps y juegos para Android', skip:'Ir a las aplicaciones', home:'Inicio', catalog:'Apps y juegos', about:'Acerca de', header:'Juega. Crea. Organiza.|Un Android más divertido.', eyebrow:'PORTAFOLIO ANDROID', heroTitle:'Productos digitales|para jugar, crear y organizar.', intro:'Apps y juegos Android creados para tu día a día.|Pequeñas ideas, grandes experiencias.', featured:'Apps y juegos destacados', all:'Todos', games:'Juegos', apps:'Aplicaciones', play:'Ver en Google Play', projects:'proyectos', noScript:'Todos los proyectos están disponibles en esta página.', aboutSummary:'Acerca de', aboutTitle:'Hecho con cuidado, por adrianobr.', aboutText:'Desarrollador Android independiente. Creo apps y juegos para hacer el día a día más práctico y divertido.', accessTitle:'Acceso no autorizado', accessText:'Esta página no está disponible directamente. Serás llevado al portal principal.', accessLink:'Ir a la página principal' },
  'zh-CN': { title:'adrianobr — Android 应用和游戏', skip:'跳到应用', home:'首页', catalog:'应用和游戏', about:'关于', header:'玩乐。创造。整理。|更有趣的 Android。', eyebrow:'ANDROID 作品集', heroTitle:'用于玩乐、创造和整理的|数字产品。', intro:'为日常生活精心打造的 Android 应用和游戏。|小创意，大体验。', featured:'精选应用和游戏', all:'全部', games:'游戏', apps:'应用', play:'在 Google Play 查看', projects:'个项目', noScript:'本页可查看所有项目。', aboutSummary:'关于', aboutTitle:'adrianobr 用心打造。', aboutText:'独立 Android 开发者，致力于让日常生活更实用、更有趣。', accessTitle:'未经授权的访问', accessText:'此页面不能直接访问。您将被带到主门户。', accessLink:'前往首页' },
  hi: { title:'adrianobr — Android ऐप्स और गेम', skip:'ऐप्स पर जाएँ', home:'होम', catalog:'ऐप्स और गेम', about:'परिचय', header:'खेलें। बनाएँ। व्यवस्थित करें।|और मज़ेदार Android।', eyebrow:'ANDROID पोर्टफोलियो', heroTitle:'खेलने, बनाने और व्यवस्थित करने के लिए|डिजिटल उत्पाद।', intro:'आपकी रोज़मर्रा की ज़िंदगी के लिए Android ऐप्स और गेम।|छोटे विचार, बड़े अनुभव।', featured:'चुनिंदा ऐप्स और गेम', all:'सभी', games:'गेम', apps:'ऐप्स', play:'Google Play पर देखें', projects:'प्रोजेक्ट', noScript:'इस पेज पर सभी प्रोजेक्ट उपलब्ध हैं।', aboutSummary:'adrianobr के बारे में', aboutTitle:'adrianobr द्वारा सावधानी से बनाया गया।', aboutText:'स्वतंत्र Android डेवलपर। रोज़मर्रा को अधिक व्यावहारिक और मज़ेदार बनाने के लिए ऐप्स और गेम बनाता हूँ।', accessTitle:'अनधिकृत पहुँच', accessText:'यह पृष्ठ सीधे उपलब्ध नहीं है। आपको मुख्य पोर्टल पर ले जाया जाएगा।', accessLink:'होम पेज पर जाएँ' },
  fr: { title:'adrianobr — Applications et jeux Android', skip:'Aller aux applications', home:'Accueil', catalog:'Applications et jeux', about:'À propos', header:'Jouer. Créer. Organiser.|Un Android plus agréable.', eyebrow:'PORTFOLIO ANDROID', heroTitle:'Des produits numériques|pour jouer, créer et organiser.', intro:'Applications et jeux Android créés pour votre quotidien.|De petites idées, de grandes expériences.', featured:'Applications et jeux en vedette', all:'Tous', games:'Jeux', apps:'Applications', play:'Voir sur Google Play', projects:'projets', noScript:'Tous les projets sont disponibles sur cette page.', aboutSummary:'À propos', aboutTitle:'Créé avec soin, par adrianobr.', aboutText:'Développeur Android indépendant. Je crée des applications et des jeux pour rendre le quotidien plus pratique et agréable.', accessTitle:'Accès non autorisé', accessText:'Cette page n’est pas disponible directement. Vous serez redirigé vers le portail principal.', accessLink:'Aller à l’accueil' },
  ar: { title:'adrianobr — تطبيقات وألعاب Android', skip:'انتقل إلى التطبيقات', home:'الرئيسية', catalog:'تطبيقات وألعاب', about:'حول', header:'العب. أنشئ. نظّم.|Android أكثر متعة.', eyebrow:'معرض أعمال ANDROID', heroTitle:'منتجات رقمية|للعب والإنشاء والتنظيم.', intro:'تطبيقات وألعاب Android مصممة لحياتك اليومية.|أفكار صغيرة وتجارب كبيرة.', featured:'تطبيقات وألعاب مميزة', all:'الكل', games:'ألعاب', apps:'تطبيقات', play:'عرض في Google Play', projects:'مشاريع', noScript:'جميع المشاريع متاحة في هذه الصفحة.', aboutSummary:'حول', aboutTitle:'صنع بعناية بواسطة adrianobr.', aboutText:'مطور Android مستقل. أصنع تطبيقات وألعاباً تجعل الحياة اليومية أكثر عملية ومتعة.', accessTitle:'وصول غير مصرح به', accessText:'هذه الصفحة غير متاحة مباشرة. سيتم نقلك إلى البوابة الرئيسية.', accessLink:'الذهاب إلى الصفحة الرئيسية' },
  'bn-BD': { title:'adrianobr — Android অ্যাপ ও গেম', skip:'অ্যাপে যান', home:'হোম', catalog:'অ্যাপ ও গেম', about:'সম্পর্কে', header:'খেলুন। তৈরি করুন। গুছিয়ে নিন।|আরও মজার Android।', eyebrow:'ANDROID পোর্টফোলিও', heroTitle:'খেলা, তৈরি ও গুছিয়ে নেওয়ার জন্য|ডিজিটাল পণ্য।', intro:'আপনার দৈনন্দিন জীবনের জন্য Android অ্যাপ ও গেম।|ছোট ধারণা, বড় অভিজ্ঞতা।', featured:'নির্বাচিত অ্যাপ ও গেম', all:'সব', games:'গেম', apps:'অ্যাপ', play:'Google Play-এ দেখুন', projects:'প্রকল্প', noScript:'এই পৃষ্ঠায় সব প্রকল্প দেখা যাবে।', aboutSummary:'adrianobr সম্পর্কে', aboutTitle:'adrianobr-এর যত্নে তৈরি।', aboutText:'স্বাধীন Android ডেভেলপার। দৈনন্দিন জীবনকে আরও ব্যবহারিক ও মজার করতে অ্যাপ ও গেম তৈরি করি।', accessTitle:'অননুমোদিত প্রবেশ', accessText:'এই পৃষ্ঠাটি সরাসরি উপলব্ধ নয়। আপনাকে মূল পোর্টালে নিয়ে যাওয়া হবে।', accessLink:'হোম পেজে যান' },
  ru: { title:'adrianobr — Приложения и игры для Android', skip:'Перейти к приложениям', home:'Главная', catalog:'Приложения и игры', about:'О проекте', header:'Играйте. Создавайте. Организуйте.|Более увлекательный Android.', eyebrow:'ПОРТФОЛИО ANDROID', heroTitle:'Цифровые продукты|для игр, творчества и порядка.', intro:'Приложения и игры Android для вашей повседневной жизни.|Маленькие идеи, большие впечатления.', featured:'Избранные приложения и игры', all:'Все', games:'Игры', apps:'Приложения', play:'Открыть в Google Play', projects:'проектов', noScript:'Все проекты доступны на этой странице.', aboutSummary:'О проекте', aboutTitle:'Создано с заботой, adrianobr.', aboutText:'Независимый Android-разработчик. Я создаю приложения и игры, чтобы сделать жизнь удобнее и интереснее.', accessTitle:'Доступ запрещён', accessText:'Эта страница недоступна напрямую. Вы будете перенаправлены на главный портал.', accessLink:'На главную страницу' },
  ur: { title:'adrianobr — Android ایپس اور گیمز', skip:'ایپس پر جائیں', home:'ہوم', catalog:'ایپس اور گیمز', about:'تعارف', header:'کھیلیں۔ بنائیں۔ منظم کریں۔|زیادہ دلچسپ Android۔', eyebrow:'ANDROID پورٹ فولیو', heroTitle:'کھیلنے، بنانے اور منظم کرنے کے لیے|ڈیجیٹل مصنوعات۔', intro:'آپ کی روزمرہ زندگی کے لیے Android ایپس اور گیمز۔|چھوٹے خیالات، بڑے تجربات۔', featured:'نمایاں ایپس اور گیمز', all:'سب', games:'گیمز', apps:'ایپس', play:'Google Play پر دیکھیں', projects:'پروجیکٹس', noScript:'تمام پروجیکٹس اس صفحے پر دستیاب ہیں۔', aboutSummary:'adrianobr کے بارے میں', aboutTitle:'adrianobr کی توجہ سے تیار کردہ۔', aboutText:'آزاد Android ڈویلپر۔ روزمرہ زندگی کو زیادہ عملی اور دلچسپ بنانے کے لیے ایپس اور گیمز تیار کرتا ہوں۔', accessTitle:'غیر مجاز رسائی', accessText:'یہ صفحہ براہ راست دستیاب نہیں ہے۔ آپ کو مرکزی پورٹل پر لے جایا جائے گا۔', accessLink:'ہوم پیج پر جائیں' }
};

export const messages = { en };
for (const [locale, copy] of Object.entries(localized)) messages[locale] = { ...en, ...copy };

export function resolveLocale(languages = []) {
  for (const requested of languages.map(language => language.replace('_', '-'))) {
    if (messages[requested]) return requested;
    const base = requested.split('-')[0].toLowerCase();
    if (base === 'pt') return /pt-pt/i.test(requested) ? 'pt-PT' : 'pt-BR';
    if (base === 'zh') return 'zh-CN';
    if (base === 'bn') return 'bn-BD';
    if (messages[base]) return base;
  }
  return 'en';
}

export function applyTranslations(document, locale) {
  const copy = messages[locale] || messages.en;
  document.documentElement.lang = locale;
  document.documentElement.dir = ['ar', 'ur'].includes(locale) ? 'rtl' : 'ltr';
  document.title = copy.title;
  document.querySelector('meta[name="description"]')?.setAttribute('content', copy.description);
  document.querySelector('meta[property="og:title"]')?.setAttribute('content', copy.title);
  document.querySelector('meta[property="og:description"]')?.setAttribute('content', copy.description);
  document.querySelectorAll('[data-i18n]').forEach(node => {
    const value = copy[node.dataset.i18n];
    if (value) node.innerHTML = value.replaceAll('|', '<br>');
  });
  document.querySelectorAll('[data-i18n-aria]').forEach(node => {
    const value = copy[node.dataset.i18nAria];
    if (value) node.setAttribute('aria-label', value);
  });
  return copy;
}
